import { useState, useEffect } from "react";
import { Link } from "react-router-dom";

function DemoPage() {
  const [offsetY, setOffsetY] = useState(0);

  /* eslint-disable */
  useEffect(() => {
    setOffsetY(window.pageYOffset);
    const handleScroll = () => {
      setOffsetY(window.pageYOffset);
    };
    window.addEventListener("scroll", handleScroll);
    return function cleanup() {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  /* eslint-enable */

  return (
    <>
      <section className="section-demo-01 bg-p"></section>
      <section className="section-demo-02 section-padding">
        <div className="container">
          <div className="grids">
            {/* left content */}
            <div className="grid md-70 sm-100">
              <div className="left-content">
                <div className="text-container">
                  <h2>AIOps</h2>
                  <div className="ss-sep-01 bg-p mt-4"></div>
                  <p className="mt-6">
                    Artificial Intelligence for IT Operations (AIOps) describes
                    the combination of big data and machine learning (ML) to
                    automate IT operation processes, including event
                    correlation, anomaly detection and root cause analysis.
                  </p>
                </div>
                <div className="text-container mt-6">
                  <h2>What is AIOps?</h2>
                  <div className="ss-sep-01 bg-p mt-4"></div>
                  <p className="mt-6">
                    AIOps stand for Artificial Intelligence for IT Operations,
                    which is using Artificial Intelligence (AI) technology to
                    operate an IT operation. The word “AIOps” was established by
                    Gartner which is the global well-known organization. They
                    discuss about AIOps platform that using Artificial
                    Intelligence & ML technology to manage all the big data
                    generated by IT system and also explain that AIOps is
                    improving IT operation performances.
                  </p>
                </div>
                <div className="text-container mt-6">
                  <h2>AIOps</h2>
                  <div className="ss-sep-01 bg-p mt-4"></div>
                  <p className="mt-6">
                    AIOps stand for Artificial Intelligence for IT Operations,
                    which is using Artificial Intelligence (AI) technology to
                    operate an IT operation. The word “AIOps” was established by
                    Gartner which is the global well-known organization. They
                    discuss about AIOps platform that using Artificial
                    Intelligence & ML technology to manage all the big data
                    generated by IT system and also explain that AIOps is
                    improving IT operation performances.
                  </p>
                  <p className="mt-6">
                    AIOps stand for Artificial Intelligence for IT Operations,
                    which is using Artificial Intelligence (AI) technology to
                    operate an IT operation. The word “AIOps” was established by
                    Gartner which is the global well-known organization. They
                    discuss about AIOps platform that using Artificial
                    Intelligence & ML technology to manage all the big data
                    generated by IT system and also explain that AIOps is
                    improving IT operation performances.
                  </p>
                  <p className="mt-6">
                    AIOps stand for Artificial Intelligence for IT Operations,
                    which is using Artificial Intelligence (AI) technology to
                    operate an IT operation. The word “AIOps” was established by
                    Gartner which is the global well-known organization. They
                    discuss about AIOps platform that using Artificial
                    Intelligence & ML technology to manage all the big data
                    generated by IT system and also explain that AIOps is
                    improving IT operation performances.
                  </p>
                  <p className="mt-6">
                    AIOps stand for Artificial Intelligence for IT Operations,
                    which is using Artificial Intelligence (AI) technology to
                    operate an IT operation. The word “AIOps” was established by
                    Gartner which is the global well-known organization. They
                    discuss about AIOps platform that using Artificial
                    Intelligence & ML technology to manage all the big data
                    generated by IT system and also explain that AIOps is
                    improving IT operation performances.
                  </p>
                </div>
              </div>
            </div>
            {/* right content */}
            <div className="grid md-30 sm-100">
              <div className="right-content">
                <ul className="bg-p">
                  <li>
                    <Link>What is AIOps?</Link>
                  </li>
                  <li>
                    <Link>What does AIOps relate with IT Operations?</Link>
                  </li>
                  <li>
                    <Link>AIOps Benefits</Link>
                  </li>
                  <li>
                    <Link>AIOps for Monitoring</Link>
                  </li>
                  <li>
                    <Link>AIOps for ITSM</Link>
                  </li>
                  <li>
                    <Link>AIOps for Automation</Link>
                  </li>
                </ul>
                <ul className="bg-s color-white">
                  <li>
                    <Link>What is AIOps?</Link>
                  </li>
                  <li>
                    <Link>What does AIOps relate with IT Operations?</Link>
                  </li>
                  <li>
                    <Link>AIOps Benefits</Link>
                  </li>
                  <li>
                    <Link>AIOps for Monitoring</Link>
                  </li>
                  <li>
                    <Link>AIOps for ITSM</Link>
                  </li>
                  <li>
                    <Link>AIOps for Automation</Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export default DemoPage;
